[Windows Build] Implement MMAP for mmap_data_loader.cpp
pytorch/executorch pull request #5164
Opened 2024-09-07 22:14 UTC by jsidewhite

There is no sys/mman.h or posix-compatible mmap() implementation on Windows.  The extension data loaders use it to map in data files, so adding an implementation.

Test-run,

   & .\cmake-out\extension\data_loader\test\Debug\extension_data_loader_test.exe --gtest_brief=1 --gtest_filter=MmapDataLoader*
   Running main() from ...\executorch\third-party\googletest\googletest\src\gtest_main.cc
   [==========] 8 tests from 1 test suite ran. (50 ms total)
   [  PASSED  ] 8 tests.

For issue #4661

2025-01-09 22:54 UTC, dbort requested changes
I'm so sorry for the delay! I totally missed this PR. This looks like a good approach.

2025-01-09 22:54 UTC, dbort commented on extension/data_loader/mman_windows.cpp
> +
- Please use angle brackets and the full path to the header
- .cpp files should include their .h file first to demonstrate that the .h files don't need earlier includes to work cleanly

```suggestion

#include <executorch/extension/data_loader/mman_windows.h>

#include <errno.h>
#include <io.h>
#include <windows.h>

```

2025-01-09 22:54 UTC, dbort commented on extension/data_loader/test/mmap_data_loader_test.cpp
> +#include <executorch/extension/data_loader/mman.h>
Please move this include down to the group on line 17. Tests should always include their header-under-test first to demonstrate that the header can be included cleanly without needing other includes.

2025-01-09 22:54 UTC, dbort commented on extension/data_loader/mman_windows.h
> +#endif
ExecuTorch is always C++, so no need for this or the matching one below

2025-01-09 22:54 UTC, dbort commented on extension/data_loader/mman_windows.h
> +#define _SYS_MMAN_H_
Please use `#pragma once`

2025-01-09 22:54 UTC, dbort commented on extension/data_loader/mman.h
> +ET_INLINE long get_os_page_size(){return sysconf(_SC_PAGESIZE)}
Not sure if this will compile without a semicolon. And the formatting is off

```suggestion
ET_INLINE long get_os_page_size() {
  return sysconf(_SC_PAGESIZE);
}
```

2025-01-09 22:54 UTC, dbort commented on extension/data_loader/mman.h
> +ET_INLINE long get_os_page_size(){return sysconf(_SC_PAGESIZE)}
Now that we're wrapping this, I'd like to return `size_t` instead of `long` to be more consistent with the types that ET uses.

2025-01-09 22:54 UTC, dbort commented on extension/data_loader/mmap_data_loader.cpp
> +#include <executorch/extension/data_loader/mman.h>
Please move this include down to the group on line 21 so that this .cpp file includes its .h file first.

2025-01-09 22:54 UTC, dbort commented on extension/data_loader/mmap_data_loader.cpp
> +#endif
Seems reasonable to always do this, if it works on unix systems; we're trying to minimize the number of ifdefs in common code.
```suggestion
  size_t map_size = range.size;
  if (range.start + map_size > file_size_) {
    // Clamp to the end of the file.
    //
    // The Windows implementation of mmap uses CreateFileMapping which returns
    // error STATUS_SECTION_TOO_BIG (0xc0000040) if we try to map past the end
    // of the last page of a file mapped in as read-only.
    map_size = file_size_ - range.start;
  }
```

2025-01-09 22:54 UTC, dbort commented on extension/data_loader/targets.bzl
> +        ],
Something like this would avoid repeating the common part.

```suggestion
        srcs = ["mmap_data_loader.cpp"] + 
            ["mman_windows.cpp"] if host_info().os.is_windows else [],
```

2025-01-09 22:54 UTC, dbort commented on extension/data_loader/targets.bzl
> +            "mman_windows.h"
Please also make this header conditional on is_windows

2025-01-31 20:33 UTC, ykhrustalev commented
@jsidewhite can I offer help on adding changes here?

2025-12-18 20:49 UTC, nil-is-all commented
@jsidewhite could you address the code changes mentioned above? Or if PR [#8916](https://github.com/pytorch/executorch/pull/8916) has addressed this, do close this issue.

2026-01-09 20:09 UTC, nil-is-all commented
@jsidewhite closing this assuming #8916 completes the changes suggested here. Re-open if necessary

2026-01-09 20:09 UTC, closed without merging