[Build] use timespec_get to get current time
pytorch/executorch pull request #5252
Opened 2024-09-10 23:27 UTC by python3kgae

Replace clock_gettime with timespec_get which works on Windows as well.

For #4661

2025-03-17 02:24 UTC, shoumikhin commented
@Tarun292, @kirklandsign can you take a look please?

2025-03-17 16:16 UTC, larryliu0820 commented
@pytorchbot rebase

2025-03-17 17:01 UTC, swolchok commented
apparently timespec_get is only available in recent versions of Android. https://github.com/confluentinc/librdkafka/issues/3044

2025-03-17 17:02 UTC, swolchok requested changes
you'll need to change this to fix the android failure, feel free to ping me for re-review

2025-03-22 22:39 UTC, python3kgae commented
> you'll need to change this to fix the android failure, feel free to ping me for re-review

Thanks for the feedback.
Updated.

2025-03-24 16:29 UTC, swolchok approved these changes

2025-03-24 16:29 UTC, swolchok commented on extension/llm/runner/util.h
> +#if defined(__ANDROID_API__) && __ANDROID_API__ < 29
comment doesn't match the code -- comment says above 29, code says 29 or later

2025-03-25 14:47 UTC, python3kgae commented on extension/llm/runner/util.h
> +#if defined(__ANDROID_API__) && __ANDROID_API__ < 29
Fixed.

2025-03-26 03:06 UTC, kirklandsign commented
Thank you!

2025-03-31 17:47 UTC, merged