[pybind] Find portable_lib.so in pip package during cmake build
pytorch/executorch pull request #5961
Opened 2024-10-07 23:39 UTC by larryliu0820

* Rename `_portable_lib.cpython-3.<distribution info>.so` to `_portable_lib.so` so it can be found by CMake `find_library()`. This can be achieved by setting `SETUPTOOLS_EXT_SUFFIX`.
* Since `executorch-config.cmake` is also being used to find installed libraries such as `executorch.a`, `xnnpack_backend.a`, add a condition to tell if `executorch-config.cmake` is being used in cmake-out or site-packages.

2024-10-07 23:58 UTC, metascroy approved these changes

2024-10-08 00:07 UTC, dbort requested changes

2024-10-08 00:07 UTC, dbort commented on build/executorch-config.cmake
> +find_library(_portable_lib_LIBRARY _portable_lib.so PATHS "${CMAKE_CURRENT_LIST_DIR}/extension/pybindings/")
I'd much rather have two configs: one for the repo, and one for the pip package. Right now, 99% of this file is inside the `if` or the `else` -- there's basically no logic shared between the two paths, so there's no real benefit to putting this logic in a single file. It also adds complexity and assumptions, like this comment describes: "if there's no .so, assume we're in the repo".

So then, you could leave the current executorch-config.cmake alone, and add a short new one like executorch-wheel-config.cmake with the wheel logic, and then rename it when copying it into the wheel.

2024-10-08 00:40 UTC, closed without merging

2024-10-10 21:59 UTC, larryliu0820 commented
@pytorchbot cherry-pick --onto release/0.4 -c critical