Added Fusion G3 NN library with kernels related to add, mul, quantize…
pytorch/executorch pull request #6738
Opened 2024-11-08 17:21 UTC by ckmadhira

…, dequantize, cat, layer norm, softmax to backends/cadence folder. Added operators to backends/cadence folder

### Summary
[PLEASE REMOVE] See [CONTRIBUTING.md's Pull Requests](https://github.com/pytorch/executorch/blob/main/CONTRIBUTING.md#pull-requests) for ExecuTorch PR guidelines.

[PLEASE REMOVE] If this PR closes an issue, please add a `Fixes #<issue-id>` line.

[PLEASE REMOVE] If this PR introduces a fix or feature that should be the upcoming release notes, please add a "Release notes: <area>" label. For a list of available release notes labels, check out [CONTRIBUTING.md's Pull Requests](https://github.com/pytorch/executorch/blob/main/CONTRIBUTING.md#pull-requests).

### Test plan
[PLEASE REMOVE] How did you test this PR? Please write down any manual commands you used and note down tests that you have written if applicable.

2024-11-08 17:23 UTC, ckmadhira commented
Fusion G3 NN library is added with kernels related to add, mul, quantize, dequantize, cat, layernorm and softmax. Operators which use these kernels are also added to backends/cadence folder

2024-11-08 18:50 UTC, zonglinpeng requested changes
Thanks for the change! Had one comment on the op namespace

2024-11-12 16:25 UTC, zonglinpeng commented on backends/cadence/aot/functions_fusion_g3.yaml
> +      kernel_name: impl::FusionG3::softmax_out
Per @hsharma35 's comment above, please use cadence::impl::G3::native::<OP_NAME> namespace

2024-11-13 14:00 UTC, ckmadhira commented on backends/cadence/fusion_g3/operators/op_add.cpp
> +namespace native {
Updated as per review comment

2024-11-13 14:03 UTC, ckmadhira commented on backends/cadence/aot/functions_fusion_g3.yaml
> +      kernel_name: impl::FusionG3::softmax_out
Updated the operator name as cadence::impl::G3::<OP_NAME>. native is not explicitly mentioned. As per kernel-library-custom-aten-kernel.md, native is automatically appended to the operators.

2024-11-13 14:04 UTC, ckmadhira commented on backends/cadence/aot/functions_fusion_g3.yaml
> +# Copyright (c) Meta Platforms, Inc. and affiliates.
Updated the operator name as cadence::impl::G3::add_out. native is not explicitly mentioned.

2024-11-14 05:56 UTC, zonglinpeng commented
please make nnlib a standalone repository @ckmadhira

2024-11-14 05:59 UTC, zonglinpeng requested changes
comment as above

2024-11-14 05:59 UTC, ckmadhira commented
> please make nnlib a standalone repository @ckmadhira

The decision is not to make the Fusion G3 NN library opensource. We are looking for a space where we can put the repo and provide exclusive access to Meta

2024-11-19 21:37 UTC, zonglinpeng commented
@ckmadhira thanks for driving nnlib to a public repo! Can you remake this PR with just the kernel updates so that I can import as a clean change? Thank you
cc @mcremon-meta

2024-11-20 05:31 UTC, ckmadhira commented
> @ckmadhira thanks for driving nnlib to a public repo! Can you remake this PR with just the kernel updates (i.e. everything except thirdparty nnlib) so that I can import as a clean change? Thank you cc @mcremon-meta

Updated Fusion G3 NN library as a submodule from opensource.

2024-11-20 16:48 UTC, hsharma35 submitted a review, later dismissed
LGTM, just needs one change:
Please make the operators in `op_*.cpp` consistent with the operators in `functions_fusion_g3.yaml`.

Thanks!

2024-11-20 16:48 UTC, hsharma35 commented on backends/cadence/aot/functions_fusion_g3.yaml
> +      kernel_name: cadence::impl::G3::add_out
@ckmadhira the name used here (`kernel_name: cadence::impl::G3::add_out`) does not match the actual kernel in `op_add.cpp` (`cadence::impl::G3::native::add_out`). Is this compiling on your end?

2024-11-20 16:48 UTC, hsharma35 commented on backends/cadence/aot/functions_fusion_g3.yaml
> +# Copyright (c) Meta Platforms, Inc. and affiliates.
With the change to operator namespace, I think this would now fail to compile. Can you please check on your end?

2024-11-20 17:20 UTC, zonglinpeng commented
Please resolve the merge conflict in .gitmodules

2024-11-20 17:20 UTC, zonglinpeng commented on backends/cadence/fusion_g3/third-party/nnlib/nnlib-FusionG3
Nice this is awesome!

2024-11-21 07:37 UTC, ckmadhira commented on backends/cadence/aot/functions_fusion_g3.yaml
> +# Copyright (c) Meta Platforms, Inc. and affiliates.
We are able to compile and verify the operator with toy model. Are you having any issue with this name space?

2024-11-21 10:39 UTC, ckmadhira commented
This is done

2024-11-21 20:06 UTC, zonglinpeng approved these changes

2024-11-21 22:15 UTC, mcremon-meta approved these changes

2024-11-22 00:40 UTC, mcremon-meta commented
@ckmadhira there are a lot of linter errors, see https://github.com/pytorch/executorch/actions/runs/11950614633/job/33350989488?pr=6738. @zonglinpeng can you share instructions on how to run the linter?

2024-11-22 21:02 UTC, zonglinpeng commented
> @ckmadhira there are a lot of linter errors, see https://github.com/pytorch/executorch/actions/runs/11950614633/job/33350989488?pr=6738. @zonglinpeng can you share instructions on how to run the linter?

https://github.com/pytorch/executorch/blob/main/CONTRIBUTING.md#lintrunner @ckmadhira

2024-11-25 17:16 UTC, zonglinpeng requested changes
there are still some lint errors, please try `lintrunner -a`
https://github.com/pytorch/executorch/actions/runs/12009466002/job/33489114504?pr=6738

2024-11-25 19:21 UTC, zonglinpeng approved these changes
fixed lint on fb side

2024-11-25 20:15 UTC, merged

2024-11-25 23:12 UTC, zonglinpeng commented on backends/cadence/aot/functions_fusion_g3.yaml
> +      kernel_name: cadence::impl::G3::native_layer_norm_out
missing quant dequant per tensor func definition. fixed in  https://github.com/pytorch/executorch/pull/7061

2024-11-25 23:12 UTC, zonglinpeng commented on backends/cadence/aot/functions_fusion_g3.yaml
> +      kernel_name: cadence::impl::G3::softmax_out
need to be _softmax to be consistent, fixed in https://github.com/pytorch/executorch/pull/7061

2024-11-25 23:12 UTC, zonglinpeng commented on backends/cadence/fusion_g3/operators/op_softmax.cpp
> +Tensor& softmax_out(
same comment, _softmax,  fixed in https://github.com/pytorch/executorch/pull/7061

2024-11-25 23:12 UTC, zonglinpeng commented on backends/cadence/fusion_g3/operators/op_quantize.cpp
> +namespace FusionG3 {
namespace needs to be G3.  fixed in https://github.com/pytorch/executorch/pull/7061

2024-11-25 23:12 UTC, zonglinpeng commented on backends/cadence/fusion_g3/operators/op_dequantize.cpp
> +void Dequantize_impl(Tensor& out,
please use all lower case  fixed in https://github.com/pytorch/executorch/pull/7061